# Generated by Django 5.0.7 on 2026-06-11 13:34

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfaceencoding',
            name='photo',
        ),
        migrations.AddField(
            model_name='studentfaceencoding',
            name='photo_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentfaceencoding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.students.models.student_photo_path),
        ),
    ]
