# Generated by Django 5.0.7 on 2026-06-12 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_auto_attendance_enabled_and_more'),
        ('students', '0004_remove_studentfaceencoding_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='classes.class')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='classes.class')),
            ],
            options={
                'verbose_name': 'Promotion History',
                'verbose_name_plural': 'Promotion History',
                'db_table': 'promotion_history',
                'ordering': ['-promotion_date'],
            },
        ),
    ]
