# Generated by Django 5.0.7 on 2026-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='auto_attendance_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic daily attendance'),
        ),
        migrations.AddField(
            model_name='class',
            name='auto_attendance_time',
            field=models.TimeField(blank=True, help_text='Time to auto-start (e.g., 08:00)', null=True),
        ),
    ]
