# Generated by Django 5.0.7 on 2026-06-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_auto_attendance_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='auto_attendance_enabled',
        ),
        migrations.RemoveField(
            model_name='class',
            name='auto_attendance_time',
        ),
    ]
