# Generated by Django 5.0.7 on 2026-06-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Locked after teacher finalizes'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='notifications_sent',
            field=models.BooleanField(default=False),
        ),
    ]
