# Generated by Django 5.0.7 on 2026-06-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_attendancesession_finalized_at_and_more'),
        ('students', '0004_remove_studentfaceencoding_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_type', models.CharField(choices=[('Present', 'Present Notification'), ('Absent', 'Absent Alert'), ('Late', 'Late Alert'), ('Leave', 'Leave Notification')], max_length=20)),
                ('attendance_status', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
                'unique_together': {('session', 'student', 'email_type')},
            },
        ),
    ]
